### ISSUE TITLE
`valac` missing

### ISSUE THREAD

**Issue by xerz-one** [sonnyp/Workbench#103]
When trying to execute a Vala program under Workbench using the `org.GNOME.Platform` runtime, `valac` is not found and the program crashes. Easiest solution is to replace the runtime to `org.gnome.Sdk`.

**Comment by sonnyp** [comment]
Thanks. Out of curiosity, how did you build Workbench?

**Comment by xerz-one** [comment]
All I did was this:

```
flatpak-builder --user --force-clean --install build-dir re.sonny.Workbench.json
```
