### ISSUE TITLE
Light and dark theme icon names are translatable

### ISSUE THREAD

**Issue by flipflop97** [sonnyp/Workbench#113]
The icon name `sun-symbolic` and `workbench-moon-rounded-symbolic` are translatable. I suppose this is an error right? Otherwise it would be nice to add an explanation for translating.

https://github.com/sonnyp/Workbench/blob/8684b56487eda79c9ff60185277a9ce87cacace5/src/window.blp#L109

https://github.com/sonnyp/Workbench/blob/8684b56487eda79c9ff60185277a9ce87cacace5/src/window.blp#L118

**Comment by sonnyp** [comment]
Thanks - fixed
