### ISSUE TITLE
Toasts Vala demo: Advanced button is never sensitive

### ISSUE THREAD

**Issue by jameswestman** [sonnyp/Workbench#114]
In the Vala code for the Toasts demo, `button_advanced.sensitive` is set to `false` but never to `true`. The JS version of the code doesn't do this, should it be `button_simple.sensitive` instead?

**Comment by sonnyp** [comment]
Yeah we disabled some Vala stuff because of https://github.com/sonnyp/Workbench/issues/110

It's confusiing, I will remove the button instead.
