### ISSUE TITLE
[Bug]: Crash when method is unsupported for class

### ISSUE THREAD

**Issue by TheEvilSkeleton** [sonnyp/Workbench#130]
Pasting this [snippet], and then pressing "Show Preview Window" in the app crashes unconditionally.

If I run it in the terminal and follow the steps above, the terminal outputs this:
```
TheEvilSkeleton@TheMainDesktop ~> flatpak run re.sonny.Workbench

(workbench-vala-previewer:23): Adwaita-WARNING **: 12:19:46.876: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Couldn't obtain the bus name.

Adwaita-gtk_window_set_titlebar() is not supported for AdwWindow
```

[snippet]: https://github.com/bottlesdevs/Bottles/blob/c2d5b1fcca1539f14b8a498db637d08f7c51efc6/src/ui/dialog-vkbasalt.ui

**Comment by sonnyp** [comment]
You're in luck - we fixed it in today's release - 42.1

Should be a `flatpak update` away from you

![image](https://user-images.githubusercontent.com/19673/178035529-878b7659-ab5f-436d-9bed-7870a51f8680.png)

**Comment by sonnyp** [comment]
Strange - i can reproduce it now.

I will have a look, could be a bug in Libadwaita. BTW you don't need to use AdwWindow if you don't need a free-form window - you can just use GtkWindow

**Comment by A6GibKm** [comment]
`Adwaita-gtk_window_set_titlebar() is not supported for AdwWindow` Is indeed a crash, so yeah one cannot use the `titlebar` property.

**Comment by sonnyp** [comment]
The reproducer does not use `titlebar`. I'm not sure where the crash is coming from.

**Comment by sonnyp** [comment]
Here is how to reproduce: 

1. Open Workbench
2. Select XML for UI
3. Paste the reproducer in UI
4. Press "Show Preview Window"
5. If it doesn't crash - repeat 3 and 4
