### ISSUE TITLE
Random crashes when editing

### ISSUE THREAD

**Issue by polyjitter** [sonnyp/Workbench#138]
Started editing a blueprint to get some info on when this happens, but can't figure out where it's happening.

This is about where it started crashing, but it only happens randomly:
```
using Gtk 4.0;
using Adw 1;

template MainWindow : Adw.ApplicationWindow {
  Box main_box {
    Adw.HeaderBar {
      [title]
      Adw.ViewSwitch  // This is where it starts happening, as I'm typing out ViewSwitcherTitle it keeps randomly crashing after a few characters
    }
  }
}
```

**Comment by polyjitter** [comment]
It's doing it not just there, either - once i finish it and try to edit, it just keeps doing it.

I think my other thing also did the same when I reached having a headerbar

**Comment by polyjitter** [comment]
BTW - Fedora Silverblue 36, installed via flatpak

**Comment by sonnyp** [comment]
Could you start Workbench from the terminal, reproduce the problem and share the output?

```sh
flatpak run re.sonny.Workbench
```

**Comment by polyjitter** [comment]
```
Gtk:ERROR:../gtk/gtkbuilder.c:1051:_gtk_builder_add: assertion failed: (GTK_IS_BUILDABLE (parent))
Bail out! Gtk:ERROR:../gtk/gtkbuilder.c:1051:_gtk_builder_add: assertion failed: (GTK
```

for my latest crash

**Comment by sonnyp** [comment]
With `42.1` (current release) I can reproduce 3 different crashes, but not with `main`.

* `assertion failed: (GTK_IS_BUILDABLE (parent))`
* exit code 139 (segfault)
* `Adwaita-gtk_window_set_titlebar() is not supported for AdwWindow` (exit code 133)

My best guess is that either the flatpak bundle I sent you was wrong, or you weren't using it when attempting to reproduce the problem.

I will release 42.2 with the fixes. Please let me know if the prolem persist (make sure you are using the right Workbench version using the `About Workbench` menu entry.
