### ISSUE TITLE
CSS not applying to the window preview

### ISSUE THREAD

**Issue by melix99** [sonnyp/Workbench#139]
When working on a GtkWindow (or a subclass of it), it seems that the CSS added in Workbench doesn't apply to the window preview.

**Comment by sonnyp** [comment]
Can you share a reproducer?

**Comment by melix99** [comment]
UI:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <object class="GtkWindow">
    <child>
      <object class="GtkButton">
        <property name="label">Test</property>
      </object>
    </child>
  </object>
</interface>
```

CSS:

```css
button {
  background: red;
}
```

Workbench version: 42.2

**Comment by sonnyp** [comment]
Thanks – I can reproduce. I will fix in the next release.

Unrelated and out of curiosity, do you use the `Code` feature of Workbench at all?

**Comment by melix99** [comment]
> Unrelated and out of curiosity, do you use the Code feature of Workbench at all?

Not really, I use Workbench only for design purposes, so I never touch that tab at all.
