### ISSUE TITLE
Add a way to format code

### ISSUE THREAD

**Issue by melix99** [sonnyp/Workbench#141]
Currently I use the trick of switching between XML and Blueprint to do that for the UI panel, but I guess it would be better to add a button and/or a shortcut to format code directly :D

**Comment by sonnyp** [comment]
An other trick is to open the code panel and trigger "Run"

**Comment by melix99** [comment]
> An other trick is to open the code panel and trigger "Run"

Mh, actually it doesn't seem to fix indentation though.


E.g. this is not fixed after pressing  "Run":
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<interface>
  <requires lib="gtk" version="4.0" />
  <object class="GtkWindow">
  <property name="default-width">360</property>
  </object>
</interface>
```
