### ISSUE TITLE
Fails to start under wayland on wsl2

### ISSUE THREAD

**Issue by MTRNord** [sonnyp/Workbench#162]
Hi, I installed it on wsl2, which uses Wayland under the hood (Using normal `flatpak install flathub re.sonny.Workbench`).

It seems like when starting, it crashes with this error:

```
Gdk-xdg_wm_base@22: error 4: xdg_surface buffer (800 x 600) does not match the configured maximized state (0 x 0)


Gdk-Message: 23:30:37.687: Error 71 (Protocol error) dispatching to Wayland display.
```

Other gtk4 Flatpak bundled applications seem to work fine. I am wondering if there is anything I could try to make this work nonetheless.

**Comment by sonnyp** [comment]
Seems like WSL is already aware of the issue?

https://github.com/microsoft/wslg/issues/646

**Comment by MTRNord** [comment]
> Seems like WSL is already aware of the issue?
> 
> https://github.com/microsoft/wslg/issues/646

Ah thanks I wasn't able to find that issue. Seems like that is indeed the same issue. :)
