### ISSUE TITLE
Install (ARM) error at submodule update

### ISSUE THREAD

**Issue by yPhil-gh** [sonnyp/Workbench#166]
Hi ; I'm trying to install Workbench ; I installed gnome-builder with apt in Ubuntu 22 Raspberry Pi edition.

Builder downloaded around a Gb during the "Installing necessary Sdk..." without errors, but after that I entered the Workbench repo directory and tried to install the dependencies as per the docs and got this error:
```
# git submodule update
Cloning into '/home/px/src/Workbench/troll'...
Submodule path 'blueprint-compiler': checked out '592ed7acab26f1633c03b0cd703a9cf2b7f09cb9'
fatal: Needed a single revision
fatal: Unable to find current revision in submodule path 'icon-development-kit-www'
```
Is Workench compatible with ARM? If it is, I may be missing some libraries..?

**Comment by sonnyp** [comment]
Could you try with GNOME Builder Flatpak?

You don't need to do `git submodule update` if you use Builder

**Comment by sonnyp** [comment]
BTW why don't you install Workbench from Flathub ?
