### ISSUE TITLE
Crash report, GtkStackPage is missing a child widget

### ISSUE THREAD

**Issue by ondrejkolin** [sonnyp/Workbench#167]
Crash on my great blueprint code. 

![Screenshot from 2022-11-03 10-06-49](https://user-images.githubusercontent.com/2377891/199682747-54fd9880-d730-4769-842f-facef0019664.png)

(base) [ondrej@fedora-ondrejk ~]$ flatpak run re.sonny.Workbench
```
(workbench-vala-previewer:23): Adwaita-WARNING **: 10:04:38.389: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
Couldn't obtain the bus name.

(re.sonny.Workbench:4): Gtk-ERROR **: 10:04:38.755: GtkStackPage '<unnamed>' [0x55ba7de0b630] is missing a child widget
```

Workbench	re.sonny.Workbench	43.0	stable	flathub	system

**Comment by ondrejkolin** [comment]
I wasn't able to remove the broken code. Maybe the Workbench could start in a "crash" mode without interpreting the broken code and displaying an error to the user.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Workbench/issues/170
