### ISSUE TITLE
Add VIM emulation

### ISSUE THREAD

**Issue by nozwock** [sonnyp/Workbench#168]
I've just recently started learning GTK and Workbench has been great for experimenting with UIs but my workflow is being hampered due to the lack of vim support.

Other GTK4 applications such as Builder, Text Editor already have vim support, so it'd be great if Workbench could have support for it as well.

If I'm not wrong, I think GtkSourceView already has [Vim emulation](https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/233) support, so I'd at least hope that it'd not be too complicated to add support for vim. I don't know much about GTK yet, so that's all the info I can provide regarding possible implementations.
Thanks!

**Comment by sonnyp** [comment]
https://gnome.pages.gitlab.gnome.org/gtksourceview/gtksourceview5/class.VimIMContext.html it looks reasonably easy/straightforward to do and a good learning opportunity

Regarding 

> It is recommended that applications display the contents of ...

Let's start by showing it in the console – with `print` for example, and then we can discuss UI.

The example needs to be translated to JavaScript but that should be pretty easy https://gitlab.gnome.org/GNOME/gjs/-/blob/master/doc/Mapping.md

If anyone is interested in giving this a try: you can join us on the Matrix channel https://app.element.io/#/room/#workbench:matrix.org

**Comment by nozwock** [comment]
Hi @sonnyp
> it looks reasonably easy/straightforward to do and a good learning opportunity
I agree, I would very much like to work on this, though since I haven't had much experience with javascript and had just started with GTK (with rust).
So I'll probably might end up taking more time to implement this, but if you're fine with that, I can start researching and learning what's required to with on this.

**Comment by sonnyp** [comment]
Workbench now has a `CodeView` object which contains the `GtkSourceView` and should make this easier.

https://github.com/sonnyp/Workbench/blob/main/src/widgets/CodeView.js

**Comment by sonnyp** [comment]
I will close this for now.

One of the target audience of Workbench is beginners. VIM mode might confuse them if they enter it by accident and it's one more option somewhere in the UI.

If advanced / VIM mode users want the nice Blueprint previewer, we should work on making a Builder or VSCode plugin instead. That is something we want to do eventually.
