### ISSUE TITLE
App failed to launch

### ISSUE THREAD

**Issue by shreyas-shriyan** [sonnyp/Workbench#172]
app failed to open with error message =>  /app/bin/workbench: line 3: /usr/lib/sdk/vala/enable.sh: No such file or directory
command used: flatpak run re.sonny.Workbench
distro : ubuntu 22.10
gnome version: 43

**Comment by sonnyp** [comment]
Can you try again after

```
flatpak install org.freedesktop.Platform.Extension.vala
```

**Comment by sonnyp** [comment]
Fixed with 43.2 available on Flathub.
