### ISSUE TITLE
Incorrect window size of Inspector

### ISSUE THREAD

**Issue by rene-coty** [sonnyp/Workbench#186]
When starting Workbench and clicking on Inspector, the appearing window is way too big for my screen (1366 * 768 - 16:9) and I can't resize it. It is a bit strange, given the fact that the content of the window doesn't take much place...
[Capture vidéo du 2023-02-01 11-33-13.webm](https://user-images.githubusercontent.com/95506494/216020590-cefe05f0-e705-4ef6-9411-b41e4d29a521.webm)

**Comment by rene-coty** [comment]
I use Fedora 37 with GNOME 43.2

**Comment by sonnyp** [comment]
I don't think it's a Workbench bug - it doesn't have control over that window.

Can you try reproducing with an other GTK4 app and open the inspector with ctrl+shift+d or ctrl+shift+i ?

**Comment by rene-coty** [comment]
I opened the inspector for the following applications : Text Editor, Newsflash and Calendar; the size of the inspector window had  good dimensions (see screenshots below)
![Capture d’écran du 2023-02-02 11-06-43](https://user-images.githubusercontent.com/95506494/216303830-e5d3a5b6-f1ee-4a7f-819e-97b9f5a42fd5.png)
![Capture d’écran du 2023-02-02 11-07-17](https://user-images.githubusercontent.com/95506494/216303838-2afba4b4-9a8a-4928-ab52-43f6514dd634.png)
![Capture d’écran du 2023-02-02 11-11-01](https://user-images.githubusercontent.com/95506494/216303844-ca0bb4c3-ce83-4ad4-b089-78355c6793ea.png)

**Comment by sonnyp** [comment]
Can you reproduce consistently with Workbench?

And, please follow these steps:

1. Open Workbench
2. Open the Inspector
3. Resize the inspector to a smaller window
4. Close Workbench
5. Open the Inspector

Is the inspector still too large?
