### ISSUE TITLE
Support external preview screenshot

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#187]

**Comment by lw64** [comment]
Is this really useful? The external preview is its own window, and with nearly every screenshot tool you can pick a window to only screenshot, which would be equal to having a screenshot button in workbench itself.

**Comment by sonnyp** [comment]
The screenshot should only include what the user is previewing. 

So if the user is previewing a Button, the window CSD shouldn't be included.

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Workbench/pull/274
