### ISSUE TITLE
Icon Library search looks weird

### ISSUE THREAD

**Issue by bertob** [sonnyp/Workbench#207]
The search bar doesn't have a border, so the content scrolls into nothingness. I'd move it to the headerbar instead.

![Capture d’écran du 2023-03-05 19-04-16](https://user-images.githubusercontent.com/1908896/222977779-65cc8cd8-ba57-4621-b729-7c7f04408417.png)

**Comment by sabbCodes** [comment]
Hi @sonnyp may I give this a try?

**Comment by sonnyp** [comment]
@sabbCodes hello

sure! Don't miss the contributing guide https://github.com/sonnyp/Workbench/blob/main/CONTRIBUTING.md

**Comment by sabbCodes** [comment]
Hi, I'm a little confused, I don't know much about GNOME.
Will my JavaScript skills suffice?

**Comment by sonnyp** [comment]
@sabbCodes JavaScript and git should be enough to get started—have a look at Workbench and join the chat room.

**Comment by iamrahul823** [comment]
@sonnyp   I would love to participate in this experimenter project by working on this issue.

**Comment by sonnyp** [comment]
@iamrahul823 great to hear, instructions to get started are here https://github.com/sonnyp/Workbench/blob/main/CONTRIBUTING.md

**Comment by cherish2003** [comment]
@sonnyp i am outreachy applicant i would to love to work on this issue can you assign me this issue ?

**Comment by sonnyp** [comment]
Not everybody can work on this issue :)

I recommend starting with https://github.com/sonnyp/Workbench/issues/69 
There is a link with instructions in how to get started.

**Comment by cherish2003** [comment]
@sonnyp  i have gone through the instruction i would like to work on this issue can you assign me

**Comment by omarY23** [comment]
> The search bar doesn't have a border, so the content scrolls into nothingness. I'd move it to the headerbar instead.
> 
> ![Capture d’écran du 2023-03-05 19-04-16](https://user-images.githubusercontent.com/1908896/222977779-65cc8cd8-ba57-4621-b729-7c7f04408417.png)

Hey @bertob. What exactly should we do with the searchbar? Can you describe a bit more

**Comment by vixalien** [comment]
I think you can use a `Gtk.SearchBar` I think that's what it's called, like the font and settings app does:

![image](https://user-images.githubusercontent.com/37999241/224559971-3b91107f-5056-49dc-9a83-3e671a162083.png)

![image](https://user-images.githubusercontent.com/37999241/224560005-a55467ad-b173-4b58-b7d3-dec1ddee62cd.png)

**Comment by bertob** [comment]
@omarY23 I'd move it to the headerbar, like e.g. in [Icon Library](https://gitlab.gnome.org/World/design/icon-library).

![image](https://user-images.githubusercontent.com/1908896/224651835-35346c68-a5a6-40cc-b54a-91ce31be2c31.png)

**Comment by vixalien** [comment]
yes! since it's always visible
