### ISSUE TITLE
crash with assertion failed: (priv->root == NULL)

### ISSUE THREAD

**Issue by AkshayWarrier** [sonnyp/Workbench#215]
I tried creating a ``Adw.PreferenceWindow`` inside a ``Gtk.Box`` something like this
```
using Gtk 4.0;
using Adw 1;

Box {
  Adw.PreferencesWindow {
  }
}
```
And Workbench crashed with this error
```
Gtk:ERROR:../gtk/gtkwidget.c:2448:gtk_widget_root: assertion failed: (priv->root == NULL)
Bail out! Gtk:ERROR:../gtk/gtkwidget.c:2448:gtk_widget_root: assertion failed: (priv->root == NULL)
```

**Comment by andyholmes** [comment]
Interesting assertion (when I went looking :slightly_smiling_face:), but I believe this is a programmer error.

You're trying to add a `GtkRoot` (i.e. a `GtkWindow`) to a `GtkBox` that has no root widget of it's own. I don't believe a `GtkWindow` can become the child of a regular widget.

**Comment by sonnyp** [comment]
@andyholmes correct but because of its nature Workbench should never crash. We have a mechanism that should prevent the crash from happening – I'm currently investigating it.

**Comment by sonnyp** [comment]
Thanks for the report.

Fixed in https://github.com/sonnyp/Workbench/pull/220
