### ISSUE TITLE
GNOME 44?

### ISSUE THREAD

**Issue by vixalien** [sonnyp/Workbench#258]
I saw [this](https://github.com/sonnyp/Workbench/commit/6b0abeec4655c583a51a3ea75ecc0044df68cef3#diff-b6d66eddcd72d10dd428b0ce45dfc933f2878d911fae958dce0b63c9bdb61554) has already been worked on, just need a new tag.

also see [the relevant PR](https://github.com/flathub/re.sonny.Workbench/pull/18)  on Workbench's flathub repo

**Comment by sonnyp** [comment]
please be patient :)
