### ISSUE TITLE
Unable to use hyphens

### ISSUE THREAD

**Issue by kdwk** [sonnyp/Workbench#26]
I'm a complete novice at programming, but I can't seem to be able to use hyphens in my code in Workbench.

![Screenshot from 2022-02-21 20-24-19](https://user-images.githubusercontent.com/39268094/154955060-0b7e5c9a-446c-4c7a-92c8-f8a5dd29b140.png)

`default-width` is a property of `GtkWindow`, but I can't seem to be able to use it in Workbench without the console throwing an error, or am I doing something wrong?

**Comment by sonnyp** [comment]
It must be `default_width` in JavaScript

Pretty cool to see Workbench has users already – I hope it's helpful in learning.

**Comment by kdwk** [comment]
Ah, I see. Incidentally, what language is the Gtk/ libadwaita documentation written for? Is there documentation (and tutorials) specifically for Gjs?

**Comment by sonnyp** [comment]
https://gjs-docs.gnome.org/

It's not perfect but getting better.

I also added JavaScript version of all examples in the GNOME developer tutorial https://developer.gnome.org/documentation/tutorials.html
