### ISSUE TITLE
workbench not respecting my monospace font setting

### ISSUE THREAD

**Issue by vixalien** [sonnyp/Workbench#262]
when installing workbench from flathub, it uses a very weird font from what i set...

![image](https://user-images.githubusercontent.com/37999241/232735308-eab6299d-a9f8-420e-a0cf-eed7eeafa314.png)

text editor works correctly and re-install doesnt fix it

![image](https://user-images.githubusercontent.com/37999241/232735599-cece035f-817d-4644-b959-19f87eae37da.png)

**Comment by vixalien** [comment]
I get it, it's bizarre since Text Editor (installed from flathub too) correctly shows my custom font...

**Comment by andyholmes** [comment]
That may be because [Text Editor has `--filesystem=host`](https://github.com/flathub/org.gnome.TextEditor/blob/master/org.gnome.TextEditor.json#L13). You could try adding that to your local manifest, to see if that changes anything.

**Comment by vixalien** [comment]
I tried changing app permissions to allow "All system files" but it still shows the weird font. Probably an issue on my end rather than with Workbench...

**Comment by vixalien** [comment]
update: I get the following update

```

(re.sonny.Workbench:4): Pango-WARNING **: 11:31:59.780: failed to create cairo scaled font, expect ugly output. the offending font is 'FreeMono 9.1669921875'

(re.sonny.Workbench:4): Pango-WARNING **: 11:31:59.780: font_face status is: file not found

(re.sonny.Workbench:4): Pango-WARNING **: 11:31:59.780: scaled_font status is: file not found

(re.sonny.Workbench:4): Pango-WARNING **: 11:31:59.782: failed to create cairo scaled font, expect ugly output. the offending font is 'FreeMono 9.1669921875'

(re.sonny.Workbench:4): Pango-WARNING **: 11:31:59.782: font_face status is: file not found

(re.sonny.Workbench:4): Pango-WARNING **: 11:31:59.782: scaled_font status is: file not found

(re.sonny.Workbench:4): Gtk-WARNING **: 11:32:05.519: Finalizing ThemeSelector 0x55ca7821b630, but it still has children left:

(re.sonny.Workbench:4): Gtk-WARNING **: 11:32:05.519:    - GtkBox 0x55ca7821c3d0
```
