### ISSUE TITLE
Webkit Example

### ISSUE THREAD

**Issue by RMcNeely** [sonnyp/Workbench#265]
Are there any examples of ways to use WebkitGTK in Workbench? I have been looking at GJS repos Webkit examples and trying to figure out how I would be able to do something like that in WorkBench but I am having no luck so far. I believe there is an issue with the versions that I don't know enough GTK development to fully comprehend. 

My goal is to make a very simple wrapper for Slack with Webkit GTK and GJS so that I can have something other than the web app  for ARM platform.

**Comment by sonnyp** [comment]
Not yet - here is one:

```js
import WebKit from "gi://WebKit?version=6.0";

const web_view = new WebKit.WebView();

web_view.load_uri("https://gnome.org");

workbench.preview(web_view);
```

> My goal is to make a very simple wrapper for Slack with Webkit GTK and GJS so that I can have something other than the web app for ARM platform.

[Tangram](https://github.com/sonnyp/Tangram/) works well on mobile

**Comment by RMcNeely** [comment]
Great! That worked perfectly once I updated the import. I

It looks like `workbench` is a global name for the app from what I can tell of the examples?

**Comment by sonnyp** [comment]
> It looks like workbench is a global name for the app from what I can tell of the examples?

Not sure what you mean. It's a global variable.

Please join the chatroom if you have more questions https://matrix.to/#/#workbench:gnome.org

**Comment by RMcNeely** [comment]
no problem thanks Sonny!

**Comment by sonnyp** [comment]
Leaving open as we need a built-in example still :+1:
