### ISSUE TITLE
Building Workbench from Source

### ISSUE THREAD

**Issue by nater1983** [sonnyp/Workbench#271]
I built Workbench from source and wasnt going to use the Flatpak app but when I try and load it I get this error..

(re.sonny.Workbench:27577): re.sonny.Workbench-CRITICAL **: 20:23:33.110: Flatpak required
Workbench is only meant to be run sandboxed in a specific target environment.
Bypassing this will exposes users to arbitrary code execution and breakage

I would like to have this application compiled from source instead of a Flatpak...

**Comment by sonnyp** [comment]
Not supported. Isn't the message clear enough?

Patch if you want but you've been warned.

I will not provide support.
