### ISSUE TITLE
Switching from XML to Blueprint fails with "invalid input"

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#279]
Steps to reproduce:

1. Select XML in `UI`
2. Remove all code in `UI`
3. Select Blueprint in `UI`

Expected result: Blueprint is selected 

Actual result: "Blueprint-CRITICAL ... Invalid input"

It is reproducible with ` `, `<></>`, ...

I'm not sure yet if we should fix this in Blueprint language server or Workbench

The error only shows in stdout, not in Workbench Console, we should look into that too.

**Comment by AkshayWarrier** [comment]
We can handle this error in the Blueprint language server as it was discussed in this [Matrix conversation](https://matrix.to/#/!hFRcFkYhvsElneVmmF:matrix.org/$gD6BQUEQDXt09i6ma9pe9gWLjbvldpV9x4fhcuXPoqk?via=matrix.org&via=gnome.org&via=envs.net)

https://gitlab.gnome.org/jwestman/blueprint-compiler/-/issues/121

**Comment by AkshayWarrier** [comment]
https://gitlab.gnome.org/jwestman/blueprint-compiler/-/merge_requests/125

**Comment by sonnyp** [comment]
@AkshayWarrier before this can be moved to done, we need to update blueprint in Workbench

We probably should wait until the next Blueprint release.

**Comment by AkshayWarrier** [comment]
Oops my bad!

**Comment by sonnyp** [comment]
@AkshayWarrier Blueprint 0.10 released

We can finish this by updating Blueprint version in

`about.js`, `re.sonny.Workbench.json` and `re.sonny.Workbench.Devel.json` 

Make sure to use the commit hash corresponding to Blueprint tag 0.10 : `2a39a16391122af2f3d812e478c1c1398c98b972`
