### ISSUE TITLE
Expose SDK documentation

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#282]
# Description

Workbench is made to work offline. 

Documentation is available in `org.gnome.Sdk.Doc` extension. We can install it by `cp` in a similar way we do with vala extension in https://github.com/sonnyp/Workbench/pull/273

We can make it available in Menu -> Platform Tools and a webkit webview

It should have search but its ok to make a follow up.

# Bookmarks

* https://floss.social/@sonny/110428662126555019

**Comment by sonnyp** [comment]
@AkshayWarrier BTW this is a fairly involved task, since you're going to be busy with exams for the next days maybe it's best to leave it to Sriyansh or José and take smaller ones?

Up to you though.

**Comment by AkshayWarrier** [comment]
Is it okay if I give it a try first to see if I can handle it because I'd love to work on this and maybe they can take over if I can't finish it?

**Comment by sonnyp** [comment]
Ofc 👍
