### ISSUE TITLE
Add tutorial-demo for GListModel with GTK & Adwaita

### ISSUE THREAD

**Issue by andyholmes** [sonnyp/Workbench#294]
Add a demo and tutorial that explains GListModel, and why models are important in GTK and Adwaita.

* [ ] Decide which APIs are most important to explain concepts and usage
* [ ] Use order that introduces concepts incrementally (e.g. model, filtering, sorting, ...)
* [ ] (Maybe) use a very simple UI to present the effect of models

 Relevant classes:

* https://docs.gtk.org/gio/iface.ListModel.html
* https://docs.gtk.org/gtk4/class.StringList.html
* https://docs.gtk.org/gtk4/class.FilterListModel.html
  * https://docs.gtk.org/gtk4/class.Filter.html
* https://docs.gtk.org/gtk4/class.SortListModel.html
  * https://docs.gtk.org/gtk4/class.Sorter.html

**Comment by sonnyp** [comment]
WE're not 100% confident with tutorials in Workbench yet but this will make an interesting experiement. And @andyholmes pointed out that we kinda of need this anyway for widgets that can be used with GListModel so we don't explain 2 things at once.

**Comment by sonnyp** [comment]
We'll make column view separate.

**Comment by andyholmes** [comment]
I've started a draft at https://gitlab.gnome.org/ewlsh/gjs-guide/-/merge_requests/163, but will have to get back to in a couple days.
