### ISSUE TITLE
Add simple GtkDrawingArea example

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#296]
Add an example for `GtkDrawingArea`, with a very simple cairo example. The example should primarily demonstrate the GTK widget, not cairo.

https://docs.gtk.org/gtk4/class.DrawingArea.html

**Comment by sonnyp** [comment]
@andyholmes wdyt of https://github.com/sonnyp/Workbench/issues/296 ?

**Comment by andyholmes** [comment]
Ah yes, that's good. The cairo example might be even a little too complex, but that's definitely enough.

Cairo is a whole topic with vectors and so on, but as long as the demo shows how to get started (including special cases like `cr.$dispose()` in GJS) that's good.
