### ISSUE TITLE
Add a style and details guide for Library Demos

### ISSUE THREAD

**Issue by andyholmes** [sonnyp/Workbench#302]
Add a simple document, with lots of examples, for how labels and other small details.

**Comment by sonnyp** [comment]
Either `CONTRIBUTING.md` or `Styleguide.md` ?

* Use `_()` for labels in Blueprint (we should also do it in Code then?)
* camelCase for functions and snake_case for values

**Comment by sonnyp** [comment]
Thanks to @andyholmes we now have https://github.com/sonnyp/Workbench/wiki/Contribution-Style-Guide
