### ISSUE TITLE
Adds Camera Demo

### ISSUE THREAD

**Issue by SoNiC-HeRE** [sonnyp/Workbench#328]
https://libportal.org/method.Portal.access_camera.html

**Comment by sonnyp** [comment]
ok so @philn says that we can create a pipelin (gst) using pipewiresrc from the portal fd

Here are a code search for `pipewiresrc` in JavaScipt:
https://github.com/search?type=code&q=pipewiresrc+lang%3AJavaScript+

I have found this https://brettviren.github.io/pygst-tutorial-org/pygst-tutorial.pdf (doesn't use portal) but we could replicate it to start with. Workbench will need `device=all` permission.

https://gstreamer.freedesktop.org/documentation/tutorials/basic/concepts.html
and
https://gstreamer.freedesktop.org/documentation/tutorials/basic/toolkit-integration.html
should help

**Comment by sonnyp** [comment]
essentially what we need is a GST pipeline that takes a pipewiresrc (what you get from libportal) and returns something we can display in Preview

maybe a stream we can feed into GtkVideo

**Comment by philn** [comment]
Here's a little demo, it's for the screencast portal, but I suppose the Camera portal might have a similar DBus interface. https://gitlab.gnome.org/-/snippets/19

**Comment by philn** [comment]
You could render the video to the gst-plugins-rs `gtk4paintablesink` maybe and embed the paintable somewhere in the app.

**Comment by sonnyp** [comment]
@philn thanks a lot.

Unfortunately, we can't use `gtk4paintablesink` because it's not part of the SDK (yet?) https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1502

This is where @SoNiC-HeRE is at https://github.com/sonnyp/Workbench/pull/348/files

Do you have another suggestion how we can display the stream?

**Comment by philn** [comment]
Well you can still bundle the gtk4 plugin in your flatpak, several apps do that :)

**Comment by philn** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/commit/b17348b08d42f6a2c588524084309d6394e7ea82

**Comment by sonnyp** [comment]
Yes, but the goal is to demonstrate GNOME technologies and how-tos.

We avoid 3rd party when possible but if you think it's best to demonstrate with `gtk4paintablesink` we'll go ahead.

**Comment by halfmexican** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/381
