### ISSUE TITLE
Console is waaaaay too big on some (HiDPI ?) screens

### ISSUE THREAD

**Issue by LyesSaadi** [sonnyp/Workbench#33]
I know there's already an issue (#30) dealing with that, but, I find it useful to report this.

On my screen 2880x1800 at 200%, this is how Workbench looks:
![image](https://user-images.githubusercontent.com/33597258/156548257-691688b8-5f89-49f3-9069-bf1abebf47cf.png)

And, if I try to resize it, it becomes even worse:
![image](https://user-images.githubusercontent.com/33597258/156548350-ba74977d-9118-4d7b-bdc2-e6da1f707c4e.png)

**Comment by sonnyp** [comment]
Closing in favor of https://github.com/sonnyp/Workbench/issues/30

FYI and until then - you can hide the Console by clicking on `Console`
