### ISSUE TITLE
Allow preview in dedicated window

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#34]
There are 2 use cases for this

1. Allow to render `<GtkWindow/>` , `AdwHeaderBar`, ...
2. Allow the user to arrange their workspace however they like (like resizing the preview window and set it to always on top)

In the future it will also enable https://github.com/sonnyp/Workbench/issues/17

The remaining question is do we need some mechanism to "Detach" the preview or should we just rely on `<GtkWindow/>` being the top level object in `UI` ?

**Comment by lw64** [comment]
If there is a mechanism needed, I could imagine another togglebutton in the headerbar with maybe multitasking-windows-symbolic icon. When enabled, you can see the ui-area and the widgets are shown there, if disabled, the area is hidden, like the other section, and the widgets are displayed in its own window.

**Comment by lw64** [comment]
I see that there is already such an "Preview" button.

**Comment by ADBeveridge** [comment]
There should probably be a detach button because of more flexibility. As for implementation, the way to go is the way Inkscape did it. (And GIMP) I think they are called dockable dialogs. (It's done via widget DND)

**Comment by sonnyp** [comment]
https://old.reddit.com/r/gnome/comments/ua1eg9/gtk4buildertool_for_libadwaita/i5vfeoq

**Comment by sonnyp** [comment]
Both use cases are covered so I will close this as done. There is a couple of caveats documented

https://github.com/sonnyp/Workbench/issues/60
https://github.com/sonnyp/Workbench/issues/59

Also, we don't have a toggle to open the inline preview in a dedicated window but if it's helpful we can open a separate ticket that is more narrow.
