### ISSUE TITLE
Namespace Adw does not contain a type called ToolbarView / NavigationSplitView / etc. 

### ISSUE THREAD

**Issue by RoepLuke** [sonnyp/Workbench#344]
Hello there,

I am relatively new into creating (and UI-prototyping) a Flatpak App for Gnome Desktops using Gtk and LibAdwaita.
I am suspecting that some newer Classes/Types/Widgets in LibAdwaita are not yet supported by Workbench (or the version of LibAdwaita in use)?

![grafik](https://github.com/sonnyp/Workbench/assets/29387023/a2ee7088-1c7c-4649-bb17-9d3608bd610e)

For Context:
In [this Doc](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/migrating-to-breakpoints.html) LibAdwaita Devs describe that:
- Adw.NavigationSplitView and Adw.NavigationView replace Adw.Leaflet
- Gtk.HeaderBar is replaced by Adw.HeaderBar
- GtkBox (when Adw.HeaderBar is its child) is replaced by Adw.ToolbarView
- etc.

When using "the old classes" (aka. GtkBox or Adw.Leaflet) it works, but it would be nice to be able to use the newer ones as well.
![grafik](https://github.com/sonnyp/Workbench/assets/29387023/b0df77cc-c727-4eb0-8757-6297153b4b54)

Or maybe I'm just doing something wrong. This is how far I've been able to trace it.

Thank you very much for your help and for maintaining Workbench and your other Apps.

_I didn't understand much by just the GTK / LibAdwaita Docs and Gnome Builders Project Templates (as all are kind of doing it their own way), but Workbench (and the Inspector) really helped me understand the concepts. Building a Blueprint in Workbench via Drag&Drop (and maybe simplifying the transfer-process from Workbench into an existing or new Gnome Builder Project) for sure would be next level and make designing a modern app based on GTK / LibAdwaita even more accessible / easier. Do you think this would be possible and if yes, how big of a Tip would be reasonable / how many working hours would be needed to make this a thing (only if you are interested ofc)?_

**Comment by sonnyp** [comment]
> I am suspecting that some newer Classes/Types/Widgets in LibAdwaita are not yet supported by Workbench (or the version of LibAdwaita in use)?

They are not even released in libadwaita. You are looking at unstable doc.
They will be available in Workbench 45.

Please refer to https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1.3/

Feel free to join the chat if you have questions.
