### ISSUE TITLE
GTK CSS language server

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#370]
A language server is a standard program that can be used by any editor (which support the Language Server Protocol) to add support for a language or feature.

https://microsoft.github.io/language-server-protocol/

With a GTK CSS Language Server, we would be able to

* show inline CSS errors (we already do but without a Language Server)
* auto-complete / suggest CSS properties
* auto-complete / suggest CSS values

GTK CSS is different from HTML CSS, we cannot use the same language server. This could also be used in GNOME Builder.

A GTK CSS Language Server should be quite straightforward to build, errors can be reported by parsing the CSS with `parsing-error` from https://docs.gtk.org/gtk4/class.CssProvider.html

I don't know if the list of CSS properties is exposed by GTK. But it doesn't change often, so it's fine to build a list. 

Prior work:
* https://github.com/microsoft/vscode-css-languageservice
* https://github.com/Microsoft/vscode/tree/main/extensions/css-language-features/server

**Comment by JCWasmx86** [comment]
This is the beginning of a CSS Language server for GTK: https://github.com/JCWasmx86/GTKCssLanguageServer (GPLv3❤️)

The editor integration for GNOME Builder is here: 

Use
```
meson _build -Dc_args="-O2" -Dplugin_clangd=disabled -Dplugin_gitgui=disabled -Dplugin_icon_installer=disabled -Dplugin_scriptdir=disabled -Dplugin_shfmt=disabled -Dplugin_swift_templates=disabled -Dplugin_texlab=disabled -Dplugin_callhierarchy=disabled -Dplugin_meson=disabled
```
for configuring meson (Unless you want to try my other plugins🤣).

This currently just takes the diagnostics from the CSS Parser.

**Comment by sonnyp** [comment]
@JCWasmx86 awesome! Looking forward to integrating in Workbench.
I think it will be particularly useful to people coming from the Web or have no idea about CSS. Because either way, the doc is not good.

And we have aucompletion coming up in Workbench

**Comment by JCWasmx86** [comment]
If anybody wants to write (maybe) GTK-specific docs for some CSS properties, feel free to do here: https://github.com/JCWasmx86/GTKCssLanguageServer/blob/main/src/docs.json
