### ISSUE TITLE
Add NavigationSplitView entry

### ISSUE THREAD

**Issue by AkshayWarrier** [sonnyp/Workbench#405]
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.NavigationSplitView.html

**Comment by sonnyp** [comment]
See "Split Views -> Navigation" in libadwaita demo (nightly)

**Comment by sonnyp** [comment]
@AkshayWarrier can you replicate the libadwaita demo? this is what we ended up doing for the Overlay Split View entry see https://github.com/sonnyp/Workbench/pull/463
