### ISSUE TITLE
Add Breakpoint/BreakpointBin entry

### ISSUE THREAD

**Issue by AkshayWarrier** [sonnyp/Workbench#407]
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.Breakpoint.html
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.BreakpointBin.html

**Comment by sonnyp** [comment]
Blueprint example \o/

https://github.com/sonnyp/Junction/blob/b6f1e09ffdfbfc861b2e3438e1f4bc9956651150/src/window.blp#L12

Please demonstrate the Blueprint syntax but also how to use breakpoint programmatically with `apply` and `unapply` signals.
