### ISSUE TITLE
The demo JS code fails to run after resetting the demo

### ISSUE THREAD

**Issue by jljouannic** [sonnyp/Workbench#42]
The demo code used to work as expected. I tried to experiment a bit but ultimately ended by resetting the demo. Now, I cannot launch it anymore. The following message appears in the console:

```
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

**Comment by sonnyp** [comment]
Can you please clarify.

> Now, I cannot launch it anymore

What is that you cannot launch? Workbench or the demo?

> The following message appears in the console:

In which console?

**Comment by jljouannic** [comment]
Sorry for the lack of detail in my first message. The demo JavaScript code does not work anymore. When I click on `Run ▶`, the error message above  appears in the Workbench console

**Comment by sonnyp** [comment]
Can you share the content of 

`~/.var/app/re.sonny.Workbench/data/re.sonny.Workbench/state.js` ?

**Comment by jljouannic** [comment]
Here it is:
```JavaScript
import Gtk from "gi://Gtk?version=4.0";
import Adw from "gi://Adw?version=1";
import system from "system";

const application = new Adw.Application({
  application_id: "com.example.Application",
});

application.connect("activate", () => {
  // create a Gtk Window belonging to the application itself
  const window = new Adw.ApplicationWindow({
    application,
    title: "Welcome to GNOME",
  });
  // show the window
  window.present();
});

const exit_code = application.run([system.programInvocationName, ...ARGV]);
system.exit(exit_code);
```

And yes, this is not the original code of the workbench demo 😅. This code comes from the [`window` component documentation](https://developer.gnome.org/documentation/tutorials/beginners/components/window.html#). It does not work when trying to run it and Workbench crash when trying to reset the demo.

But everything is fine once I restart the Workbench. Resetting the demo works again. Sorry for wasting your time

**Comment by sonnyp** [comment]
No problem.

It is unfortunate that some examples do not work in Workbench. Only examples with `Application` should be affected.

I wrote the JavaScript examples for the documentation, if you spot any mistake or something not working in Workbench, feel free to let me know here.

**Comment by sonnyp** [comment]
This code example will now run fine and `Application` as well as `system.exit` can be used in the next version of Workbench

https://github.com/sonnyp/Workbench/commit/89d619a0707e26abfd9332ba5e382cd42d9ff2fe
https://github.com/sonnyp/Workbench/commit/12078fae6ef235ff160fde9a0553b19a2a5e91fd
