### ISSUE TITLE
Network Monitor demo

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#454]
https://docs.gtk.org/gio/iface.NetworkMonitor.html

See also @pwithnall talk https://www.youtube.com/watch?v=WVWrllJQJ_s&t=18094s

**Comment by pwithnall** [comment]
Note that there are a couple of features you could focus on with the network monitor, both of which have associated UI consequences.
 * Network connectivity status: is the app offline, online but in a captive portal, or fully online? How should the app present that to the user? (That is not covered in my talk)
 * Network metered status: if the app is online, is the network metered (costing the user per unit data). How should the app present _that_ to the user? (That is covered in my talk)
