### ISSUE TITLE
Memory Monitor demo

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#455]
https://docs.gtk.org/gio/iface.MemoryMonitor.html

See also @pwithnall talk https://www.youtube.com/watch?v=WVWrllJQJ_s&t=18094s

**Comment by pwithnall** [comment]
I’ve opened an issue against the HIG, as we could end up coming up with some patterns for low memory presentation in apps: https://gitlab.gnome.org/Teams/Design/hig-www/-/issues/159. However, of the three things in my talk, this is the one which is least likely to need to be exposed to the user in the UI. It’s more likely that it’ll just result in some internal changes in the app, like dropping caches when memory is low.

**Comment by sonnyp** [comment]
GJS will now use this to trigger the garbage collector. 

But we can still make a demo that empty some fake memory cache or something
