### ISSUE TITLE
Power Profile Monitor

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#456]
https://docs.gtk.org/gio/iface.PowerProfileMonitor.html

See also @pwithnall talk https://www.youtube.com/watch?v=WVWrllJQJ_s&t=18094s

**Comment by pwithnall** [comment]
I’ve opened an issue against the HIG, as we could end up coming up with some patterns for power-saver status presentation in apps: https://gitlab.gnome.org/Teams/Design/hig-www/-/issues/159

**Comment by sonnyp** [comment]
There was a person named Jason at the Workbench workshop who started working on this. I wonder if they'll see this :) 

I'll try to find a way to get in touch with them to know if they're willing to finish the demo.
