### ISSUE TITLE
Running the js script does not clean the runtime environment

### ISSUE THREAD

**Issue by HarryMichal** [sonnyp/Workbench#50]
**What happened?**

Registering a new class in a script causes problems from second execution forward due to the type already being registered.

![image](https://user-images.githubusercontent.com/17991284/165497441-9ffc5a82-b53f-4e9c-a0b7-ba39b26a2686.png)

**How to reproduce?**

```js
import GObject from "gi://GObject";

const MyObject = GObject.registerClass({
    GTypeName: "MyObject"
  }, class MyObject extends GObject.Object {
    _init(params) {
      super._init(params);
    }
  },
);
```

Run script at least twice.

**Comment by sonnyp** [comment]
Yeah with the current architecture, some things causes issues such as this or `setInterval`.

I plan on moving execution in its own process to avoid the problem all together but that means we will always need to preview in a separate window :disappointed:

**Comment by sonnyp** [comment]
This specific problem will be fixed in the next release.

I have added an override for now until we support out-of-process execution.
