### ISSUE TITLE
Translation not possible

### ISSUE THREAD

**Issue by JonasLoos** [sonnyp/Workbench#54]
Currently helping with translations seems to not be possible:
![image](https://user-images.githubusercontent.com/33965649/167296711-94dce9cf-587d-4bda-b78b-0261276dce95.png)
(https://hosted.weblate.org/projects/workbench/workbench/)

If it is possible again, I would be interested in helping to translate Workbench to German.

**Comment by sonnyp** [comment]
Should be fine now.

Thanks!
