### ISSUE TITLE
Do not request network at build time

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#591]
Our Flatpak manifests currently require network at build time (`--share=network`). This is not allowed on Flathub, and we need to solve that before GNOME 45 if we want to be included in the release notes.

https://github.com/sonnyp/Workbench/blob/main/build-aux/re.sonny.Workbench.Devel.json
https://github.com/sonnyp/Workbench/blob/main/build-aux/modules/gst-plugins-rs.json

I could really use some help here :pray: 

@Hofer-Julian since this is Cargo related, would you be interested / available to look into it?

**Comment by Hofer-Julian** [comment]
We could have a look if someone else uses gst-plugins-rs on flathub and copy their setup
