### ISSUE TITLE
Default demo shouldn't have Code

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#61]
So that the default is a simpler Gtk/CSS editor

It will look simpler / more accessible to beginner and I expect most application developers use Workbench for GTK/CSS only.

**Comment by lw64** [comment]
Why?

**Comment by sonnyp** [comment]
Should have written a description

So that the default is a simpler Gtk/CSS editor

It will look simpler / more accessible to beginner and I expect most application developers use Workbench for GTK/CSS only.

**Comment by sonnyp** [comment]
We could also instead hide `Code` and `Style` by default to let the user explore 

https://github.com/sonnyp/Workbench/issues/67

But they can explore other demos so maybe not

**Comment by sonnyp** [comment]
We could also instead hide `Code` and `Style` by default to let the user explore 

https://github.com/sonnyp/Workbench/issues/67

But there is also the library for exploration, so maybe not

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Workbench/issues/67 & https://github.com/sonnyp/Workbench/issues/75 fixes the concern here
