### ISSUE TITLE
It should not be possible to disable all panels

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#64]
This is what happens if you disable all panels

One should be the minimum

![image](https://user-images.githubusercontent.com/19673/168424951-39a0ecfd-fb01-44d6-90b7-70111b92ec9b.png)

**Comment by lw64** [comment]
Maybe the last button should get insensitive?

But if you want to disable the last one and switch to another one disabling all first is a use case.

Another solution would be to have a statuspage that says "open a panel".

**Comment by sonnyp** [comment]
> But if you want to disable the last one and switch to another one disabling all first is a use case.

Good point.

WDYT of

![image](https://user-images.githubusercontent.com/19673/168477134-80222593-4492-478c-b86b-5e7b465007d8.png)

I think it looks very fancy and since it's slightly off (without looking bad) I think users will understand its a placeholder - finding you're wait out is easy enought that we don't need to explain IMHO.
