### ISSUE TITLE
Extract Manuals into a standalone app

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#640]
We should extract the offline documentation viewer “Manuals” into a standalone app so that

1. it benefits everybody, not just Workbench users
2. it's easier to work on it by removing Workbench complexity

To-do

1. [x] Create a new GitHub repo with Workbench code as template @sonnyp 
2. [x] Remove everything that's not related to Manuals @sonnyp 
3. [x] Adjust metadata / credits / doap / metainfo / ... @sonnyp 
4. [x] Add collaborators 
5. [x] Publish to Flathub :)
6. [x] Remove Manuals code from Workbench
7. [ ] Add Manuals as a module to Workbench

I will co-maintain with @AkshayWarrier - @andyholmes would you be interested too?

Once we have a repo we can create issues for the good ideas that have been floating around:

* [x] Mobile https://github.com/sonnyp/Workbench/issues/627
* [ ] Tabs
* [ ] Browser 
* [ ] DevDocs
* [x] Bookmarks to Rust/GJS/Vala/PyGObject/...
* [ ] Support redirecting "https://docs.gtk.org/gtk4/class.AppChooserButton.html" to local offline doc
* [ ] Support navigating to http URLs
* [ ] Support the docset format https://zealdocs.org/
* [ ] Support download/viewing multiple sdk docs version
* [x] #703
* [ ] Add “Find” (in current page)
* [ ] Add full text search

**Comment by andyholmes** [comment]
It seems like there might be some overlap with Devhelp here. Is the plan to replace it, or maybe use libdevhelp somehow?

**Comment by andyholmes** [comment]
Maybe we should see what Christian had planned for Builder? Seems like a library that could be shared between Workbench/Manuals/Builder would be a good way to share efforts.
