### ISSUE TITLE
The screenshot button should be hidden when the preview window is not open

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#65]
When the preview is not open - the screeshot button does nothing.

Lets make it `sensitive: false` or hide it in that situation.

![image](https://user-images.githubusercontent.com/19673/168438845-82688185-9fa9-40b4-bea2-0322d2e6f2a7.png)

**Comment by anarayner** [comment]
I would like to fix this issue

**Comment by sonnyp** [comment]
Great to hear.

Here is a small guide

1. Fork Workbench

2. Get Workbench to run from source

Install / start GNOME Builder from https://beta.flathub.org/apps/details/org.gnome.Builder and select the option "Clone repository" - use your fork URL.

Make sure Workbench runs properly by pressing on the Play button in Buillder.

3. Understand and reproduce the bug in Workbench

1. Open the "Application Window" Library. 
2. Click on the Screenshot button

Nothing happens because the preview doesn't exist yet – user must click on "Show Preview Window"

4. Fix the bug!

Good luck and let me know if you get stuck

**Comment by sonnyp** [comment]
Also, feel free to drop by the room if you have questions https://matrix.to/#/#workbench:matrix.org

**Comment by sonnyp** [comment]
@anarayner are you still interested in taking care of this?

**Comment by anarayner** [comment]
> @anarayner are you still interested in taking care of this?

I had issues installing Builder. You can take it

**Comment by sonnyp** [comment]
Fixed in https://github.com/sonnyp/Workbench/commit/218ca703d15d2db3c7ab45c21b7d22078f0bc6a7
