### ISSUE TITLE
Unable to run Python demos with SourceView in the ui file

### ISSUE THREAD

**Issue by UrtsiSantsi** [sonnyp/Workbench#713]
(process:101): Gtk-ERROR **: 01:30:56.799: failed to add UI: .:8:1 Invalid object type 'GtkSourceView'

**Comment by theCapypara** [comment]
I can't reproduce this, are you using the Flatpak based development environment and did you import GtkSource?
```py
import gi
gi.require_version("GtkSource", "5")
from gi.repository import GtkSource

print(GtkSource.View)
```
prints
```
<class 'gi.repository.GtkSource.View'>
```

**Comment by theCapypara** [comment]
If you are running Workbench via GNOME Builder it will use the Flatpak. 

That is odd, so with that exact snippet I shared you get an error?

**Comment by theCapypara** [comment]
Why do you have a `$` in front of GtkSourceView? I'm pretty sure it should be just `Gtk.SourceView`, also note the `.`.
