### ISSUE TITLE
[Flatpak|KDE] No icon showing on taskbar

### ISSUE THREAD

**Issue by v38armageddon** [sonnyp/Workbench#72]
**How?**
I just launching Workbench and constat on my taskbar, there is not a icon.

**Steps to reproduce:**

1. Launch Workbench (flatpak run re.sonny.workbench)
2. Look at the taskbar.

**Informations**
Version: 1.2.0
Install method: Flatpak via Terminal

**Screenshot**
![Screenshot_20220518_174500](https://user-images.githubusercontent.com/69727502/169085828-9e782847-9241-4c76-ae9f-c25f1a6f6e77.png)

**Other**
This is not a big issue, just a detail.
I just want to say: Thank you for creating this software. I can learn more easily how to make GTK application.

**Comment by sonnyp** [comment]
Likely not an issue in Workbench

> Thank you for creating this software. I can learn more easily how to make GTK application.

You're welcome :)
