### ISSUE TITLE
Languages support table

### ISSUE THREAD

**Issue by UrtsiSantsi** [sonnyp/Workbench#752]
Add new demos to the list when available.
When working on language support for demo add 🚧 or pull request number if available. Replace it with check mark when merged.

|Demo|JavaScript|Vala|Rust|Python|
|:--------|:------------:|:-----:|:-----:|:--------:|
|About Window|✔|✔|✔|✔|
|Accessibility|✔|✘|✔|✘|
|Account|✔|✔|✔|✘|
|Action Bar|✔|✘|✔|✘|
|Actions|✔|✘|✘|✔|
|Advanced Buttons|✔|✔|✔|✔|
|Animation|✔|✘|✘|✘|
|Audio|✔|✔|✘|✘|
|Avatar|✔|✘|✘|✔|
|Banner|✔|✘|✔|✘|
|Boxed Lists|✔|✔|✔|✔|
|Box|✔|✔|✘|✘|
|Breakpoints|✔|✔|✔|✔|
|Button|✔|✔|✔|✔|
|CSS Gradients|✔|✘|✘|#724|
|Calendar|✔|✘|✔|✔|
|Camera|✔|✘|✘|✘|
|Carousel|✔|✔|✘|#719|
|Center Box|✔|✔|✔|✔|
|Checkboxes|✔|✘|✔|✔|
|Clamp|✔|✘|✘|✘|
|Color Dialog|✔|✔|✘|#725|
|Color Picker|✔|✔|✔|#741|
|Column View|✔|✘|✘|✘|
|Custom Widget|✔|✘|✘|✘|
|Dialogs|✔|✔|✘|#743|
|Drag and Drop|✔|✔|✘|✘|
|Drawing Area|✔|✘|✔|✘|
|Drop Down|✔|✔|✘|✘|
|Drop Zone|✔|✔|✘|✘|
|Editable Label|✔|✔|✔|✔|
|Email|✔|✔|✔|✘|
|Emoji Chooser|✔|✘|✔|✔|
|Event Controllers|✔|✔|✘|✘|
|File Monitor|✔|✘|✘|✘|
|Flow Box|✔|✔|✔|#744|
|Font Dialog|✔|✘|✘|✘|
|Frame|✔|✘|✘|✘|
|Grid|✔|✘|✔|✘|
|HTTP Image|✔|✔|✔|✘|
|HTTP Request|✔|✘|✘|✘|
|Header Bar|✔|✔|✔|✔|
|Image|✔|✔|✔|✔|
|Label|✔|✘|✘|#747|
|Launcher|✔|✘|✔|✘|
|Level Bars|✔|✘|✘|✘|
|Link Button|✔|✘|✔|✔|
|List Model|✔|✔|✘|✘|
|List View Widgets|✔|✔|✘|✘|
|Location|✔|✔|✘|✘|
|Map|✔|✘|✔|✘|
|Memory Monitor|✔|✘|✘|#746 |
|Menu Button|✔|✘|✔|✔|
|Menu|✔|✘|✘|#751 |
|Navigation Split View|✔|✔|✔|✔|
|Navigation View|✔|✘|✔|✘|
|Network Monitor|✔|✘|✘|✘|
|Notification|✔|✔|✘|✘|
|Open File|✔|✘|✘|✘|
|Overlay Split View|✔|✘|✔|✘|
|Overlay|✔|✔|✔|✔|
|Pango Markup|✔|✔|✔|✔|
|Picture|✔|✔|✔|✘|
|Platform Tools|✔|✔|✔|✔|
|Popovers|✔|✘|✔|✔|
|Power Profile Monitor|✔|✘|✘|✘|
|Preferences Window|✔|✔|✘|✘|
|Progress Bar|✔|✘|✘|✘|
|Radio Buttons|✔|✘|✔|✔|
|Revealer|✔|✘|✘|#748 |
|Save File|✔|✘|✘|✘|
|Scale|✔|✔|✘|✘|
|Screencast|✔|✘|✘|✘|
|Screenshot|✔|✔|✘|✘|
|Scrolled Window|✔|✘|✘|✘|
|Search|✔|✘|✘|#742|
|Select Folder|✔|✘|✘|✘|
|Separator|✔|✘|✔|✔|
|Session Monitor and Inhibit|✔|✘|✘|🚧|
|Source View|✔|✔|✘|#757|
|Spell Checker|✔|✘|✘| #758|
|Spin Button|✔|✘|✔|#756|
|Spinner|✔|✔|✔|✔|
|Stack|✔|✔|✘|#755|
|Status Page|✔|✘|#750|#754|
|Styling with CSS|✔|✘|✔|✔|
|Switch|✔|✘|✔|#753|
|Tab View|✔|✘|✔|#737|
|Text Colors|✔|✘|✔|#735|
|Text Fields|✔|✔|✘|#734|
|Text View|✔|✔|✘|#733|
|Toasts|✔|✔|✘|#732|
|Toggle Button|✔|✘|✔|✔|
|Toolbar View|✔|✘|✘|#730|
|Tooltip|✔|✘|✘|✔|
|Video|✔|✔|✔|#728|
|View Switcher|✔|✔|✔|#726|
|Wallpaper|✔|✔|✔|✘|
|Web View|✔|✘|✔|✘|
|WebSocket Client|✔|✔|✘|✘|
|Welcome|✔|✔|✔|✔|
|Window|✔|✔|✔|✔|

**Comment by gregorni** [comment]
@UrtsiSantsi This is great! I did some small formatting to make it more visual, but this is a really good system! Thanks!
