### ISSUE TITLE
Translate Library demos to Vala

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#82]
Should be a faithful / close equivalent.

**Comment by sonnyp** [comment]
@benpocalypse99 would you be interested in taking this?

**Comment by sonnyp** [comment]
@benpocalypse you expressed interested in taking care of this in https://github.com/sonnyp/Workbench/pull/38#issuecomment-1122846477 - is that still the case?

**Comment by benpocalypse** [comment]
Yes!

So sorry for the delay in getting to this, I had to travel for work last week and getting home was no easy feat. I think I can knock this out this week.

**Comment by sonnyp** [comment]
That's great to hear. `main` should run out of the box with GNOME Builder.

You will simply need to add a `.vala` file in each `src/Library/Demos` folder and add that file to `src/workbench.gresource.xml`.

Also – all demos are in the public domain, by contributing to them, you waive any copyright claim. https://creativecommons.org/publicdomain/zero/1.0/

**Comment by sonnyp** [comment]
https://github.com/sonnyp/Workbench/pull/101
