### ISSUE TITLE
Replace confirm dialog with toasts

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#84]
![image](https://user-images.githubusercontent.com/19673/169614875-12da39d9-440f-4cd3-991d-ffa1b4f1f260.png)

let's replace this with a "undo" toast instead

**Comment by lw64** [comment]
Should the toast appear in the library-window or the main window?

**Comment by sonnyp** [comment]
main window because we need to be able to offer undo when other things happen
