### ISSUE TITLE
Inform users when a permission is required for a demo

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#915]
Currently, Workbench is considered as "probably safe" by Flathub and GNOME Software.

The reason it is not considered "Safe" is because we require network and audio permission (via `--socket=pulseaudio` and `--share=network`. Those are not strictly required to use Workbench and are only needed for a handful of demos. In addition, we would also like to add a permission for gamepads https://github.com/workbenchdev/demos/pull/88

Eventually there will be portals for all of these things but until then we need static permissions.

Let's

1. remove those permissions so that Workbench is considered safe 
2. add a mechanism for demos to advertise which permissions they need - maybe `flatpak-finish-args: ["--socket=fallback-x11"]` in `main.json`
3. when a needed permission is not enabled, Workbench should show a dialog on "Run" to explain what this is about and how to enable the permission using `flatpak overrides`

Since overrides are permanent - it should be a one time thing only anyway.

**Comment by bragefuglseth** [comment]
Hey, and sorry for the late response! I can have a shot at it if you can provide some textual content / instruction set to design the dialog around. I'm not too knowledgeable on that stuff :smiley:

**Comment by bragefuglseth** [comment]
Sorry for the late response again! This is on my todo list.

**Comment by bragefuglseth** [comment]
Any thoughts on this? I think it's nice to give a brief overview of what people are actually doing when running the command. The explanation list might also be a useful introduction to the Flatpak permission system for aspiring app developers. The descriptions may not be 100% accurate; you can change those as you see fit.

![permissions](https://github.com/user-attachments/assets/0f23d34a-b983-4045-ab35-ce56d553ae18)

**Comment by bragefuglseth** [comment]
I thought it would be nice to include to reassure people that it will only affect their account or whatever, but feel free to exclude it :slightly_smiling_face: 

Here's the illustration SVG:

![permissions](https://github.com/user-attachments/assets/7357de5f-e5fd-4a3e-8c3a-5d56387a0104)

**Comment by Mikenux** [comment]
@bragefuglseth: Thanks for redirecting me to the issue!

The problem is really asking to reduce protection. This shouldn't be asked from a (fully) sandboxed app at all. This shows bad practice for acquiring permissions that reduce the app sandbox.

To do this properly, a portal is needed. And, unfortunately, the proposed design, although nice and well done, is not good for a portal because of the words "Needed", "needs", "Please", which induce obligation.
