### ISSUE TITLE
TypeScript needs a code formatter

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#956]
In https://github.com/workbenchdev/Workbench/pull/946 we replaced Biome with typescript-language server

Formatting was provided by Biome and it works fine with TypeScript, unfortunately using 2 language servers isn't easily done. 

We should add a formatter to `typescript-language-server` or use Biome and typescript-language-server together.

We could also use `prettier` which is mostly compatible with Biome formatter.

**Comment by vixalien** [comment]
I might be wrong but I think `tsserver` has a built-in formatter.  I think it's the default in VSCode and you can invoke it manually

![image](https://github.com/workbenchdev/Workbench/assets/37999241/d97b73db-2315-47d0-804d-cad76e3d294c)

Also evidenced by https://github.com/typescript-language-server/typescript-language-server/issues/10

But in practice it seems less than perfect for the task. It's very lax.
