### ISSUE TITLE
main branch fails to compile

### ISSUE THREAD

**Issue by benpocalypse** [sonnyp/Workbench#97]
It looks like there is a file in the source tree missing: `./src/troll/util.js`

I thought perhaps it was a submodule, but I don't see one after snooping around a bit. The folder in the source tree is currently empty.
![Screenshot from 2022-05-21 20 08 20](https://user-images.githubusercontent.com/6274196/169672948-e6f3bd12-126c-4827-be70-7616464aed23.png)

The relevant error is this:
`[7/7] Generating workbench_gresource with a custom command
FAILED: src/workbench.gresource 
/usr/bin/glib-compile-resources ../../../../../../../../../Projects/Workbench/src/workbench.gresource.xml --sourcedir src --sourcedir ../../../../../../../../../Projects/Workbench/src --internal --generate --target src/workbench.gresource --dependency-file src/workbench.gresource.d
../../../../../../../../../Projects/Workbench/src/workbench.gresource.xml: Failed to locate “troll/src/util.js” in any source directory.
ninja: build stopped: subcommand failed.
`

**Comment by sonnyp** [comment]
```
cd Workench
git submodule update
```

should solve it - I will add to documentation

**Comment by benpocalypse** [comment]
I tried that before I initially posted this issue. There is no output when I do a `git submodule update` so I got a bit more aggressive and think I found the problem:

`
benpocolypse@desktop:~/Projects/Workbench$ git submodule update
benpocolypse@desktop:~/Projects/Workbench$ git submodule foreach git pull
benpocolypse@desktop:~/Projects/Workbench$ git submodule sync
benpocolypse@desktop:~/Projects/Workbench$ git submodule update --init --recursive
Submodule 'src/blueprint-compiler' (https://gitlab.gnome.org/sonny/blueprint-compiler.git) registered for path 'blueprint-compiler'
Submodule 'icon-development-kit-www' (git@gitlab.gnome.org:Teams/Design/icon-development-kit-www.git) registered for path 'icon-development-kit-www'
Submodule 'troll' (https://github.com/sonnyp/troll.git) registered for path 'src/troll'
Cloning into '/home/flecko/Projects/Workbench/blueprint-compiler'...
Cloning into '/home/flecko/Projects/Workbench/icon-development-kit-www'...
Warning: Permanently added the ED25519 host key for IP address '8.43.85.27' to the list of known hosts.
git@gitlab.gnome.org: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@gitlab.gnome.org:Teams/Design/icon-development-kit-www.git' into submodule path '/home/flecko/Projects/Workbench/icon-development-kit-www' failed
Failed to clone 'icon-development-kit-www'. Retry scheduled
Cloning into '/home/flecko/Projects/Workbench/src/troll'...
Cloning into '/home/flecko/Projects/Workbench/icon-development-kit-www'...
git@gitlab.gnome.org: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@gitlab.gnome.org:Teams/Design/icon-development-kit-www.git' into submodule path '/home/flecko/Projects/Workbench/icon-development-kit-www' failed
Failed to clone 'icon-development-kit-www' a second time, aborting
`
Not sure what to do about that though. And sorry to be a bother if it's something obvious.

**Comment by sonnyp** [comment]
This should fix it https://github.com/sonnyp/Workbench/commit/ef051f96838e47fec17760e17206d144d339a14e

Can you pull `main` and try again?

> Not sure what to do about that though. And sorry to be a bother if it's something obvious.

Not at all

**Comment by benpocalypse** [comment]
That did the trick! I hadn't realized 1 of the 3 modules was using the `git@` syntax.

Thanks - I'll  sync my fork up and get to work on the Demos tomorrow.
