### ISSUE TITLE
Error when switching from Blueprint to XML, then back

### ISSUE THREAD

**Issue by carbon-starlight** [sonnyp/Workbench#994]
In "Boxed Lists" example, if you switch "UI" window to XML, then try to go back to Blueprint, the console throws an error 

`(re.sonny.Workbench:5): Blueprint-CRITICAL **: 12:50:21.313: unsupported XML tag: <items>`

**Comment by sonnyp** [comment]
https://gitlab.gnome.org/jwestman/blueprint-compiler/-/issues/139
